prepare_base_model:
  augmentation: True
  image_size: [224, 224, 3]     # as per VGG16 input
  batch_size: 16
  include_top: False
  epochs: 50
  classes: 2
  weights: imagenet
  learning_rate: 0.0005

