artifacts_root: artifacts/

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: research/Normal&Tumor.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  base_model_weights_path: artifacts/prepare_base_model/base_model_weights.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_model.h5